- name: demo on data types
  hosts: local
  connection: local
  vars:
    PROGRAM: "DEVSECOPS WITH AWS"
    DURATION: 140
    IS_LIVE: true
    DETAILS:
      MONTHS: 4
      TRAINER: "SivaKumar Reddy"
    TOPICS:
    - LINUX
    - SHELL
    - Ansible
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: |
        program: {{ PROGRAM }}
        duration: {{ DURATION }}
        Is Live?: {{ IS_LIVE }}
        details: {{ DETAILS }}
        topics: {{ TOPICS }}